// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AiConversation struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Title     sql.NullString `json:"title"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type AiMessage struct {
	ID             int64          `json:"id"`
	ConversationID int64          `json:"conversation_id"`
	Role           string         `json:"role"`
	Content        string         `json:"content"`
	Filtered       sql.NullInt64  `json:"filtered"`
	FilterReason   sql.NullString `json:"filter_reason"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type FilterCategory struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullInt64  `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type GroupMessage struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Notification struct {
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
	Type      string        `json:"type"`
	Title     string        `json:"title"`
	Message   string        `json:"message"`
	Read      sql.NullInt64 `json:"read"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type SecurityFilter struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	FilterType  string         `json:"filter_type"`
	Pattern     string         `json:"pattern"`
	Action      string         `json:"action"`
	IsActive    sql.NullInt64  `json:"is_active"`
	AppliesTo   sql.NullString `json:"applies_to"`
	Severity    sql.NullString `json:"severity"`
	CreatedBy   sql.NullInt64  `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type SecurityLog struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	FilterID        sql.NullInt64  `json:"filter_id"`
	OriginalContent string         `json:"original_content"`
	ActionTaken     string         `json:"action_taken"`
	IpAddress       sql.NullString `json:"ip_address"`
	UserAgent       sql.NullString `json:"user_agent"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type Session struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type SystemConfig struct {
	ID          int64          `json:"id"`
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Description sql.NullString `json:"description"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Nomina       string         `json:"nomina"`
	PasswordHash string         `json:"password_hash"`
	Nombre       string         `json:"nombre"`
	Departamento sql.NullString `json:"departamento"`
	Approved     sql.NullInt64  `json:"approved"`
	IsAdmin      sql.NullInt64  `json:"is_admin"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
