// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AnswerQuestion(ctx context.Context, arg AnswerQuestionParams) (sql.Result, error)
	ApproveSubmission(ctx context.Context, arg ApproveSubmissionParams) (sql.Result, error)
	ApproveUser(ctx context.Context, id int64) (sql.Result, error)
	CountActiveFilters(ctx context.Context) (int64, error)
	CountActiveKnowledge(ctx context.Context) (int64, error)
	CountActiveSessions(ctx context.Context) (int64, error)
	CountConversationMessages(ctx context.Context, conversationID int64) (int64, error)
	CountGroupMessages(ctx context.Context) (int64, error)
	CountPendingQuestions(ctx context.Context) (int64, error)
	CountPendingSubmissions(ctx context.Context) (int64, error)
	CountSecurityLogsByUser(ctx context.Context, userID int64) (int64, error)
	CountSecurityLogsToday(ctx context.Context) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID int64) (int64, error)
	CountUserConversations(ctx context.Context, userID int64) (int64, error)
	// ============ AI CONVERSATIONS ============
	CreateAIConversation(ctx context.Context, arg CreateAIConversationParams) (AiConversation, error)
	// ============ AI MESSAGES ============
	CreateAIMessage(ctx context.Context, arg CreateAIMessageParams) (AiMessage, error)
	CreateFilterCategory(ctx context.Context, arg CreateFilterCategoryParams) (FilterCategory, error)
	// ============ GROUP CHAT ============
	CreateGroupMessage(ctx context.Context, arg CreateGroupMessageParams) (GroupMessage, error)
	// ============ KNOWLEDGE BASE ============
	CreateKnowledge(ctx context.Context, arg CreateKnowledgeParams) (KnowledgeBase, error)
	// ============ KNOWLEDGE SUBMISSIONS ============
	CreateKnowledgeSubmission(ctx context.Context, arg CreateKnowledgeSubmissionParams) (KnowledgeSubmission, error)
	// ============ NOTIFICATIONS ============
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ============ SECURITY FILTERS ============
	CreateSecurityFilter(ctx context.Context, arg CreateSecurityFilterParams) (SecurityFilter, error)
	// ============ SECURITY LOGS ============
	CreateSecurityLog(ctx context.Context, arg CreateSecurityLogParams) (SecurityLog, error)
	// ============ SESSIONS ============
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// ============ UNANSWERED QUESTIONS ============
	CreateUnansweredQuestion(ctx context.Context, arg CreateUnansweredQuestionParams) (UnansweredQuestion, error)
	// ============ USERS ============
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteConfig(ctx context.Context, key string) (sql.Result, error)
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) (sql.Result, error)
	DeleteExpiredSessions(ctx context.Context) (sql.Result, error)
	DeleteFilterCategory(ctx context.Context, id int64) (sql.Result, error)
	DeleteKnowledge(ctx context.Context, id int64) (sql.Result, error)
	DeleteOldNotifications(ctx context.Context) (sql.Result, error)
	DeleteSecurityFilter(ctx context.Context, id int64) (sql.Result, error)
	DeleteSession(ctx context.Context, token string) (sql.Result, error)
	DeleteUser(ctx context.Context, id int64) (sql.Result, error)
	DeleteUserSessions(ctx context.Context, userID int64) (sql.Result, error)
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (sql.Result, error)
	GetActiveFilterCategories(ctx context.Context) ([]FilterCategory, error)
	GetActiveKnowledge(ctx context.Context) ([]GetActiveKnowledgeRow, error)
	GetActiveSecurityFilters(ctx context.Context) ([]SecurityFilter, error)
	GetAdminUserIDs(ctx context.Context) ([]int64, error)
	GetAllConfig(ctx context.Context) ([]SystemConfig, error)
	GetAllKnowledge(ctx context.Context) ([]GetAllKnowledgeRow, error)
	GetAllQuestions(ctx context.Context) ([]GetAllQuestionsRow, error)
	GetAllSecurityFilters(ctx context.Context) ([]GetAllSecurityFiltersRow, error)
	GetAllSubmissions(ctx context.Context) ([]GetAllSubmissionsRow, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetApprovedUsers(ctx context.Context) ([]GetApprovedUsersRow, error)
	// ============ SYSTEM CONFIG ============
	GetConfig(ctx context.Context, key string) (string, error)
	GetConversation(ctx context.Context, arg GetConversationParams) (AiConversation, error)
	GetConversationByID(ctx context.Context, id int64) (AiConversation, error)
	GetConversationMessages(ctx context.Context, conversationID int64) ([]GetConversationMessagesRow, error)
	// ============ STATISTICS ============
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	// ============ FILTER CATEGORIES ============
	GetFilterCategories(ctx context.Context) ([]FilterCategory, error)
	GetFilteredMessages(ctx context.Context, limit int64) ([]GetFilteredMessagesRow, error)
	GetGroupMessagesSince(ctx context.Context, id int64) ([]GetGroupMessagesSinceRow, error)
	GetKnowledgeByCategory(ctx context.Context, category sql.NullString) ([]GetKnowledgeByCategoryRow, error)
	GetKnowledgeByID(ctx context.Context, id int64) (KnowledgeBase, error)
	GetKnowledgeContext(ctx context.Context) ([]GetKnowledgeContextRow, error)
	GetPendingQuestions(ctx context.Context) ([]GetPendingQuestionsRow, error)
	GetPendingSubmissions(ctx context.Context) ([]GetPendingSubmissionsRow, error)
	GetPendingUsers(ctx context.Context) ([]GetPendingUsersRow, error)
	GetQuestionByID(ctx context.Context, id int64) (UnansweredQuestion, error)
	GetRecentConversationMessages(ctx context.Context, arg GetRecentConversationMessagesParams) ([]GetRecentConversationMessagesRow, error)
	GetRecentGroupMessages(ctx context.Context, limit int64) ([]GetRecentGroupMessagesRow, error)
	GetRecentSecurityLogs(ctx context.Context, limit int64) ([]GetRecentSecurityLogsRow, error)
	GetSecurityFilterByID(ctx context.Context, id int64) (SecurityFilter, error)
	GetSecurityFiltersByAppliesTo(ctx context.Context, appliesTo sql.NullString) ([]SecurityFilter, error)
	GetSecurityFiltersByType(ctx context.Context, filterType string) ([]SecurityFilter, error)
	GetSecurityLogsByDateRange(ctx context.Context, arg GetSecurityLogsByDateRangeParams) ([]GetSecurityLogsByDateRangeRow, error)
	GetSecurityLogsByUser(ctx context.Context, arg GetSecurityLogsByUserParams) ([]GetSecurityLogsByUserRow, error)
	GetSecurityStats(ctx context.Context) (GetSecurityStatsRow, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetSubmissionByID(ctx context.Context, id int64) (GetSubmissionByIDRow, error)
	GetSubmissionsByUser(ctx context.Context, submittedBy int64) ([]KnowledgeSubmission, error)
	GetUnreadNotifications(ctx context.Context, userID int64) ([]Notification, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByNomina(ctx context.Context, nomina string) (User, error)
	GetUserConversations(ctx context.Context, userID int64) ([]GetUserConversationsRow, error)
	GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notification, error)
	IgnoreQuestion(ctx context.Context, arg IgnoreQuestionParams) (sql.Result, error)
	MarkAllNotificationsRead(ctx context.Context, userID int64) (sql.Result, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (sql.Result, error)
	RejectSubmission(ctx context.Context, arg RejectSubmissionParams) (sql.Result, error)
	RejectUser(ctx context.Context, id int64) (sql.Result, error)
	SetConfig(ctx context.Context, arg SetConfigParams) (sql.Result, error)
	ToggleSecurityFilter(ctx context.Context, arg ToggleSecurityFilterParams) (sql.Result, error)
	TouchConversation(ctx context.Context, id int64) (sql.Result, error)
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (sql.Result, error)
	UpdateFilterCategory(ctx context.Context, arg UpdateFilterCategoryParams) (sql.Result, error)
	UpdateKnowledge(ctx context.Context, arg UpdateKnowledgeParams) (sql.Result, error)
	UpdateSecurityFilter(ctx context.Context, arg UpdateSecurityFilterParams) (sql.Result, error)
	UpdateUserDepartamento(ctx context.Context, arg UpdateUserDepartamentoParams) (sql.Result, error)
	// ============ PASSWORD CHANGE ============
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
